services:
  - type: web
    name: baixa-backend
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: GITHUB_REPOSITORY
        value: laurourbano/baixa
      - key: GITHUB_BACKUP_PATH
        value: cards_backup.json
      - key: GITHUB_TOKEN
        sync: false
